### ISSUE TITLE
Discuss use of strict types

### ISSUE THREAD

**Issue by michaelcullum** [cs-extended/fig-standards#7]
As per IRC, we need to discuss this on the ML.

@KorvinSzanto 

```
<Korvin> MichaelC, "All files MUST declare strict types."
<MichaelC> yes
<Korvin> I don't agree with that
<MichaelC> Why not?
<Korvin> There's a reason why it's optional, I don't think we should try to circumvent internals by forcing it always on
<MichaelC> We aren't circumventing internals by forcing it always on
<MichaelC> We are saying, if you're following PSR-12, then you're doing it this way
<MichaelC> within a project, this is the kind of thing to be standardised within coding style guidelines
<Korvin> I don't agree.
<MichaelC> I spoke with a few people about it at PHP NW and they agreed
<MichaelC> including Andrea
<MichaelC> each project needs to decide if it's going to do strict types or not
<MichaelC> and that belongs in their coding guidelines
<MichaelC> right?
<MichaelC> That's what PSR-2 and PSR-12 are supposed to act as
<Korvin> so then are we going to provide a PSR that allows people to leave it off?
<Korvin> because it doesn't make sense to me that compliance with PSR-12 requires strict types be enabled.
<MichaelC> You can say PSR-12 without requiring strict types declarations in the same way you can say PSR-2 with tabs
<MichaelC> If we start to debate this, that's exactly what it will become
<Korvin> Well, we can leave it up to the list to decide
<MichaelC> Okay
<MichaelC> I'll put something up tomorrow
<Korvin> Okay
<-- villav (~Thunderbi@72.54.189.186) has quit (Ping timeout: 250 seconds)
<Korvin> I surely hope that my future isn't plagued with "<?php declare(strict_types=1); ?>"
<MichaelC> Ah so it's that bit you're not happy about
<MichaelC> That was the bit I wasn't sure about
<Korvin> no
<Korvin> I'm unhappy about it all
<MichaelC> (Files that contain more than just PHP)
<Korvin> I'm unhappy all the way back to the internals discussion
<Korvin> :) I just don't think that we need to make this assertion.
<MichaelC> I think it needs to be consistent within a project
<MichaelC> like tabs/spaces
<MichaelC> and one way needs to be picked to go in the spec
<MichaelC> then people can just say they follow it and then add exceptions
<Korvin> I agree that it needs to be consistent, but I think we can do that without forcing that everyone enable it
<MichaelC> We aren't forcing anything on anyone
<MichaelC> We didn't force spaces on the entire php world
<MichaelC> Some projects simply won't adopt PSR-2, and those that want PSR-2 with tabs just state it as such
<MichaelC> It's better to have it,then have projects have it as an exception when they want to do the opposite
<MichaelC> than leave it open
<Korvin> I don't think that you should have to make an exception to not declare strict typing
<MichaelC> where it will become inconsistent within projects
<Korvin> Why not define it as either or than? If you define it, define it in every php file
<MichaelC> what do you mean
<Korvin> Why can't we say "If declaring strict types anywhere in your project, you must declare it everywhere" or something like that?
<MichaelC> hm
<MichaelC> That's not a bad idea
<MichaelC> I'll prod pmjones and see what discussions when on with PSR-2 about why they didn't phrase stuff like that in PSR-2 with tabs/spaces etc.
<Korvin> to me it's different than that, it's omission vs adding everywhere. It feels to me like "MUST have a docblock comment at the top of every file"
```

**Comment by michaelcullum** [comment]
Note to self: I think we should add an exception anyway for automated tests

**Comment by cryptiklemur** [comment]
"Why can't we say "If declaring strict types anywhere in your project, you must declare it everywhere" or something like that?"

This makes the most sense to me. That way we don't have to have a second standard for people who aren't using it, and people who shouldn't (PHP 5).

**Comment by michaelcullum** [comment]
@keradus @gsherwood Your thoughts on that from a CS fixer point of view?

**Comment by gsherwood** [comment]
A couple of points from me on this, without voting for the use of strict types or not:

A lot of people do define their own coding standard for PHPCS, and a lot of people did complain that PSR-2 required the use of spaces over tabs. I ended up creating a custom standard people could download and use with PHPCS and PHPCBF (the auto-fixer built into PHPCS) to enforce the use of tabs and to replace tabs with spaces: https://gist.github.com/gsherwood/9d22f634c57f990a7c64

Then they complained a brace conditions. Some others complained about indent rules. You can't win this game. You just need to encourage people to use PSR-12 as a start point, then exclude the bits they don't like and include other checks they want.

The same thing is easily done with strict types. Either a custom standard can remove the strict type check and make it fully optional, or you can not include strict types in PSR-12 and a custom standard can include a check to enforce it. It is 100% a coding standards decision, so you just need to decide if it will be pushed onto the larger PHP community with PSR-12.

Personally, I work in an enterprise software environment where PHP7 just isn't an option for the supported distros. PHPCS itself can't go PHP7-only either, so I would already be removing the strict types rules from PSR-12 if you put it in there. But I can always remove the exception in x years time when most clients move to a RH distro with PHP7 and long-term support. And I already have a custom standard for PHPCS development that merges many coding standards together.

> "Why can't we say "If declaring strict types anywhere in your project, you must declare it everywhere" or something like that?"

This is the bit you really wanted feedback on, and I think it is very hard to enforce by an automated tool, both for checking and fixing. Most checking that PHPCS does is done on single files. A lot of it in real-time inside IDEs and text editors. Having to scan the entire project every time just to determine if any file inside it uses strict types is a waste of time and would make the tool unusable. It also assumes people have properly excluded libraries, frameworks and other includes from their custom coding standard to ensure that we don't enforce strict types just because a library file has it.

The decision to start using strict types should be hard-coded into a coding standard for everyone to read and follow. This proposed rule doesn't do that and should not be included in a coding standard. I could easily see it in a coding guidelines document that is used by developers to build their own coding standards, but not in a named standard like PSR-12 that is designed to be enforced by an automated tool.

Hope that helps. Ping me any time if you find my feedback useful. One thing I love talking about is coding standards. We must be a small bunch of people :)

**Comment by KorvinSzanto** [comment]
> The decision to start using strict types should be hard-coded into a coding standard for everyone to read and follow. This proposed rule doesn't do that and should not be included in a coding standard. I could easily see it in a coding guidelines document that is used by developers to build their own coding standards, but not in a named standard like PSR-12 that is designed to be enforced by an automated tool.

The problem I have with it is that strict types is a language feature and not a coding style issue. This is more similar to saying something like "fopen() ONLY no file_get_contents()". We're not making a judgement to increase readability of code, we're just saying that strict types is better than weak types.

I can see why you say it's difficult for static analysis tools to determine, I think we should just not make any judgement at all on this. Maybe we can have a separate PSR that speaks to which language features are okay to use.

Thanks for the comments!
Korvin

**Comment by gsherwood** [comment]
> The problem I have with it is that strict types is a language feature and not a coding style issue. This is more similar to saying something like "fopen() ONLY no file_get_contents()". We're not making a judgement to increase readability of code, we're just saying that strict types is better than weak types.

In my opinion, that's exactly the kind of thing that should be included in the coding standard for a project. Limiting a coding standard to just formatting (i.e., reducing it to a style guide only) is a pretty normal thing, but I think it is a mistake.

But yes, doing this for a generic coding standard designed to be used by multiple projects (ideally, almost all projects in some way) is probably taking things too far. You'd need to have a really good reason for every inclusion.

So while I love the idea of including rules in a coding standard that go beyond formatting, it's probably still best to have a generic style guide at the core and then let projects build upon it for things like using one function over another, maximum nesting levels, and maybe even strict types.

**Comment by KorvinSzanto** [comment]
@gsherwood Agreed with every point completely.

**Comment by cryptiklemur** [comment]
> that's exactly the kind of thing that should be included in the coding standard for a project

Agreed, and this is a coding **style** standard. 

https://github.com/cs-extended/fig-standards/blob/task/psr-12/proposed/extended-coding-style-guide.md#extended-coding-style-guide

**Comment by gsherwood** [comment]
> Agreed, and this is a coding style standard.

I totally agree with you, hence my comment about keeping this as a core style guide and (hopefully) encouraging projects to build on that to create a complete project coding standard.

If I personally had to make the decision, I wouldn't put strict types in as a requirement for this standard. I think it goes too far away from a core style guide. But I would encourage projects to still consider its usage, although I'm not sure is PSRs can do something like that. Sort of an "optional extras" section.

**Comment by michaelcullum** [comment]
@gsherwood Thank you very much for all your comments, they are always very welcome. After a lengthy discussion on IRC which was going on simultaneously I'll be dropping the line about requiring strict types.

**Comment by keradus** [comment]
Good decision. But since strict types are considered to be good, can't we suggest it like "All files **SHOULD** declare strict types." ?

**Comment by michaelcullum** [comment]
Coding standards should ideally only include MUST/MUST NOT in my opinion but I'd be interested to hear from a tools POV how that works.

https://mwop.net/blog/2013-02-27-resigned-from-php-fig.html explains some reasoning for this.

**Comment by gsherwood** [comment]
When I'm doing a PHPCS check, I interpret MUST/MUST NOT to mean "error" and SHOULD/SHOULD NOT to mean "warning".

So if you include a line like "All files SHOULD declare strict types" I would assume that a tool like PHPCS should produce a warning for all files that don't declare strict types.

**Comment by cryptiklemur** [comment]
@keradus 

I just want to reiterate, this is a coding style guide, not a coding standard. I don't really think this is the place for saying whether or not strict types should/must be enabled.
